### ISSUE TITLE
Allocatable cpu resource will be lost when kubelet restart

### ISSUE THREAD

**Issue by antzjm** [nokia/CPU-Pooler#58]
**Describe the bug**
Once kubelet.service restarted, the exclusive and share cpu resource will lost. This problem can be resolved by restartling cpu-device-plugin pod.

**To Reproduce**
1. systemctl restart kubelet.service
2. kubectl decribe node to observe exclusive and share cpu resouce.

**Expected behavior**

**Additional context**

**Relevant SW info**
- Linux distro
- Kubernetes version
- Other

**Comment by Levovar** [comment]
yes it works like that, but it is by design

in the Device Plugin - Kubelet interaction Kubelet is the server not the client, so it is the DP which needs to seek out the Kubelet. Kubelet does not know about the DPs
also Kubelet does not store the registered devices in a persistent store, only in memory. so when you restart the Kubelet these devices are lost, and Pooler needs to register itself again with the new Kubelet process
when you restart Pooler it does exactly that

hope this answers

**Comment by antzjm** [comment]
@Levovar  Thanks for your answer. I also want to know it there any workaround to avoid this phenomenon. This design about cpu pooler and kubelet  may not be stable on production environment.

**Comment by antzjm** [comment]
@Levovar There is not 100% about losing resource when restart kubelet. Sometimes I restart kubelet, the exclusive and share cpu resouce of nodes do not loss.

**Comment by Levovar** [comment]
hmm, interesting. I will ask our internal production team if they have seen this, and whether they have a workaround. I guess one could add a liveness probe checking if the resources managed by Pooler show up in the Allocatable field of the Node it is running on, and exit with error if not

but, other than that registration is a one-time even in other DP reference implementations too as far as I can tell

**Comment by antzjm** [comment]
I think it's should be an optimizing point for cpu pooler's next development. There are also sriov NIC device-plugin and  in my infra, but it will not loss resource when kubelet restart.

**Comment by Levovar** [comment]
I think it might be because of this:
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/dd65f3f65dacaecb01176e139d4373d909a217ef/pkg/resources/server.go#L289

it effectively does the same what I proposed above to be added in the form of a liveness probe: it checkes for signs of kubelet restart, and if it happened it restarts itself to re-trigger registration
I think an independent probe based restart is a cleaner and more native solution, so we will add that to the Deployment specification of the DP

**Comment by antzjm** [comment]
I have look up the DP document.  Can I add liveness probe by configure cpu-device-plugin's deamoset yaml or only modify source code can make it use?

**Comment by antzjm** [comment]
`[cbis-admin@hztt24f-oe19-1-a2-allinone-0 ~]$ sudo ls -l /var/lib/kubelet/device-plugins
total 24
srwxr-xr-x. 1 root root     0 Feb 14 06:52 cpudp_exclusive_numa_0_pool.sock
srwxr-xr-x. 1 root root     0 Feb 14 06:52 cpudp_shared_pool.sock
-rw-r--r--. 1 root root     0 Feb 13 05:11 DEPRECATION
-rw-------. 1 root root 22900 Feb 14 06:52 kubelet_internal_checkpoint
srwxr-xr-x. 1 root root     0 Feb 13 05:11 kubelet.sock
srwxr-xr-x. 1 root root     0 Feb 13 05:11 nokia.k8s.io_sriov_ens1f1.sock
srwxr-xr-x. 1 root root     0 Feb 13 05:11 nokia.k8s.io_sriov_vfio_ens1f1.sock
[cbis-admin@hztt24f-oe19-1-a2-allinone-0 ~]$ sudo systemctl restart kubelet
[cbis-admin@hztt24f-oe19-1-a2-allinone-0 ~]$ sudo ls -l /var/lib/kubelet/device-plugins
total 24
srwxr-xr-x. 1 root root     0 Feb 14 07:16 cpudp_exclusive_numa_0_pool.sock
srwxr-xr-x. 1 root root     0 Feb 14 07:16 cpudp_shared_pool.sock
-rw-r--r--. 1 root root     0 Feb 14 07:16 DEPRECATION
-rw-------. 1 root root 22900 Feb 14 07:16 kubelet_internal_checkpoint
srwxr-xr-x. 1 root root     0 Feb 14 07:16 kubelet.sock
srwxr-xr-x. 1 root root     0 Feb 14 07:16 nokia.k8s.io_sriov_ens1f1.sock
srwxr-xr-x. 1 root root     0 Feb 14 07:16 nokia.k8s.io_sriov_vfio_ens1f1.sock
`

**Comment by antzjm** [comment]
![image](https://user-images.githubusercontent.com/32393135/107870911-ce1d9000-6ed7-11eb-9dee-7209116efe83.png)
Here is result  I tested. Not every kubelet restart will loss resource. So I guess it not the root cause about liveness probe.

**Comment by antzjm** [comment]
@Levovar  Can you share me the example of liveness probe?

**Comment by Levovar** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

**Comment by antzjm** [comment]
@Levovar tks for your support. Hope cpupooler will solve this issue in next generation :)
